### ISSUE TITLE
Shuffle doesn't seem to work

### ISSUE THREAD

**Issue by mattgig** [otacke/h5p-jigsaw-puzzle#2]
It seems that at the moment the puzzle parts are stacked according to their position in the original picture. 

The top puzzle part always goes into the bottom right corner, the second one next to the top one and so on. With 8 parts the puzzles are stacked like 8, 7, 6, ... And then you can just drag them like this:

1 2 3 4
5 6 7 8

It it possible that randomizeTiles in h5p-jigsaw-puzzle-content.js (line 508) is not executed?

**Comment by otacke** [comment]
@mattgig Could you possibly give me more information like you normally would on the H5P forum? In particular:

- What browser in what version on what operating system are you using?
- Are there any errors visible in the development console (usually opened by pressing F12 except in Safari where the dev tools are called "Web Inspector" and need to be activated first)?
- Can you provide a link to the platform where you are experiencing this?

**Comment by otacke** [comment]
@mattgig Oooh, now I understand what you mean :-D I should fix that ... Give me a second ...

**Comment by otacke** [comment]
@mattgig Should be fixed in version 0.4.3. Please download the demo content from https://www.olivertacke.de/labs/2022/01/17/you-would-jig-if-you-saw-that-puzzle/ and upload it to your site in order to update the library. H5P should clear its internal cache automatically when you open existing content again, but reloading once without using the browser's cache (usually with shift-F5) won't hurt.

Would be cool if you gave me some feedback about whether this was the issue and if you think it's fixed now.

**Comment by otacke** [comment]
@mattgig Sorry, just introduced another bug ... Please wait for 0.4.4

**Comment by otacke** [comment]
@mattgig Now this should do, v0.4.4.

**Comment by mattgig** [comment]
You new version correctly shuffles the pieces of the puzzle. I tried it out with a 3 x 2 puzzle, and every time a differnt piece landed on top.
Thanks a lot for fixing this so quickly.

**Comment by otacke** [comment]
@mattgig Don't mention it! And thanks for reporting. I fear, more often people notice something weird, but they don't invest a couple of minutes to file a bug report - or simply don't know that or how this is possible.
